#server.servlet.session.cookie.max-age=1800
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 60m
spring:
  config:
    import:
      - secret.yml
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379

kakao:
  map:
    url: "https://dapi.kakao.com"